// Compiled by ClojureScript 1.9.521 {:static-fns true, :optimize-constants true}
goog.provide('pages.dave');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('hoplon.core');
goog.require('layout.content_block');
goog.require('layout.header_block');
goog.require('layout.body_text');
goog.require('image.hoplon');
goog.require('social.hoplon');
goog.require('wheel.abn.core');
goog.require('wheel.link.hoplon');
pages.dave.content = (function pages$dave$content(){
return new cljs.core.PersistentVector(null, 8, 5, cljs.core.PersistentVector.EMPTY_NODE, [image.hoplon.cropped.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.cst$kw$src,"https://s3-ap-southeast-2.amazonaws.com/dim-valley-public/dave-photo.jpg",cljs.core.cst$kw$width,"100%",cljs.core.cst$kw$height,"400px",cljs.core.cst$kw$css,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$margin_DASH_bottom,"4px",cljs.core.cst$kw$filter,"saturate(0)"], null)], 0)),layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0(),social.hoplon.icon_links.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.cst$kw$linkedin,"https://www.linkedin.com/in/dmeister/",cljs.core.cst$kw$github,"https://github.com/thedavidmeister",cljs.core.cst$kw$medium,"https://medium.com/@thedavidmeister",cljs.core.cst$kw$twitter,"https://twitter.com/thedavidmeister"], 0))], 0)),layout.header_block.header("David Meister (Dave)","Owner and consultant at Dim Valley Pty. Ltd. and owner and CTO at Nice Feature Pty. Ltd."),layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("I believe...") : hoplon.core.h2.call(null,"I believe...")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Simple beats complex."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Quality is a process."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Machines are better machines than humans."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Effective systems are composed from effective parts."], 0))], 0)),layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Experience") : hoplon.core.h2.call(null,"Experience")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Commercial") : hoplon.core.h3.call(null,"Commercial")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__24644 = (function (){var G__24650 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("10+ years total") : hoplon.core.strong.call(null,"10+ years total"));
var G__24651 = " professional web experience.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24650,G__24651) : hoplon.core.li.call(null,G__24650,G__24651));
})();
var G__24645 = (function (){var G__24652 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Started out") : hoplon.core.strong.call(null,"Started out"));
var G__24653 = " making cool MySpace pages for local indie bands.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24652,G__24653) : hoplon.core.li.call(null,G__24652,G__24653));
})();
var G__24646 = (function (){var G__24654 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("3 years building") : hoplon.core.strong.call(null,"3 years building"));
var G__24655 = " ";
var G__24656 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://furstmedia.com.au/","Furst Media's");
var G__24657 = " publishing platform (10% MoM growth).";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24654,G__24655,G__24656,G__24657) : hoplon.core.li.call(null,G__24654,G__24655,G__24656,G__24657));
})();
var G__24647 = (function (){var G__24658 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("5 years owning and operating") : hoplon.core.strong.call(null,"5 years owning and operating"));
var G__24659 = " my previous digital agency, ";
var G__24660 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2(wheel.abn.core.abr_search_url("58147061121"),"Godel");
var G__24661 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24658,G__24659,G__24660,G__24661) : hoplon.core.li.call(null,G__24658,G__24659,G__24660,G__24661));
})();
var G__24648 = (function (){var G__24662 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("2 years as chief solutions architect") : hoplon.core.strong.call(null,"2 years as chief solutions architect"));
var G__24663 = " at ";
var G__24664 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/","Equiem");
var G__24665 = " ";
var G__24666 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/2016","(100% YoY growth)");
var G__24667 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__24662,G__24663,G__24664,G__24665,G__24666,G__24667) : hoplon.core.li.call(null,G__24662,G__24663,G__24664,G__24665,G__24666,G__24667));
})();
var G__24649 = (function (){var G__24668 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Current owner and CTO") : hoplon.core.strong.call(null,"Current owner and CTO"));
var G__24669 = " of Dim Valley and Nice Feature.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24668,G__24669) : hoplon.core.li.call(null,G__24668,G__24669));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$6(G__24644,G__24645,G__24646,G__24647,G__24648,G__24649) : hoplon.core.ul.call(null,G__24644,G__24645,G__24646,G__24647,G__24648,G__24649));
})()], 0)),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Open source") : hoplon.core.h3.call(null,"Open source")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__24670 = (function (){var G__24675 = (function (){var G__24679 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://drupalcores.com/countries.html","6th in Australia");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__24679) : hoplon.core.strong.call(null,G__24679));
})();
var G__24676 = " for contributions to ";
var G__24677 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.drupal.org/","Drupal");
var G__24678 = " core.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24675,G__24676,G__24677,G__24678) : hoplon.core.li.call(null,G__24675,G__24676,G__24677,G__24678));
})();
var G__24671 = (function (){var G__24680 = (function (){var G__24684 = "Fully automated ";
var G__24685 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/radiant-brook","bitcoin trading bot");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__24684,G__24685) : hoplon.core.strong.call(null,G__24684,G__24685));
})();
var G__24681 = " written in ";
var G__24682 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://symfony.com/","PHP/Symfony");
var G__24683 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24680,G__24681,G__24682,G__24683) : hoplon.core.li.call(null,G__24680,G__24681,G__24682,G__24683));
})();
var G__24672 = (function (){var G__24686 = (function (){var G__24690 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://xoroshiro.di.unimi.it/","Xoroshiro128+");
var G__24691 = " pseudorandom number generator";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__24690,G__24691) : hoplon.core.strong.call(null,G__24690,G__24691));
})();
var G__24687 = " implemented ";
var G__24688 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/xoroshiro128","in clojure");
var G__24689 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24686,G__24687,G__24688,G__24689) : hoplon.core.li.call(null,G__24686,G__24687,G__24688,G__24689));
})();
var G__24673 = (function (){var G__24692 = (function (){var G__24694 = "The ";
var G__24695 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__24696 = " web framework";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$3(G__24694,G__24695,G__24696) : hoplon.core.strong.call(null,G__24694,G__24695,G__24696));
})();
var G__24693 = ", contributing to development, support and documentation.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24692,G__24693) : hoplon.core.li.call(null,G__24692,G__24693));
})();
var G__24674 = (function (){var G__24697 = (function (){var G__24703 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/dim-valley","This website");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__24703) : hoplon.core.strong.call(null,G__24703));
})();
var G__24698 = " built in ";
var G__24699 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__24700 = ", leveraging a ton of ";
var G__24701 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/wheel","my own intellectual property");
var G__24702 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__24697,G__24698,G__24699,G__24700,G__24701,G__24702) : hoplon.core.li.call(null,G__24697,G__24698,G__24699,G__24700,G__24701,G__24702));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$5 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$5(G__24670,G__24671,G__24672,G__24673,G__24674) : hoplon.core.ul.call(null,G__24670,G__24671,G__24672,G__24673,G__24674));
})()], 0))], 0)),layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Availability") : hoplon.core.h2.call(null,"Availability")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Building ",wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://estimate-work.com/","Estimate Work")," is currently my primary focus, limiting my overall availability, but I am happy to provide services to new and existing clients on an ad-hoc basis."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["I am available ",(hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("up to 3 days per week") : hoplon.core.strong.call(null,"up to 3 days per week"))," to contract on projects with a clearly defined scope and deliverables."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["My preference is for most or all project work to be ",(hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("conducted remotely") : hoplon.core.strong.call(null,"conducted remotely")),", using common telecommute technologies such as Google Hangouts, Slack, Flowdock, etc. to stay connected and in sync."], 0))], 0)),layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Rate card") : hoplon.core.h2.call(null,"Rate card")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["1 hour = $AUD 120 + GST",(hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null)),"1 day (prebooked) = $AUD 800 + GST"], 0))], 0)),layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Case studies") : hoplon.core.h2.call(null,"Case studies")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Estimate Work") : hoplon.core.h3.call(null,"Estimate Work")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Estimate Work is a project planning tool designed to assist small teams working with hard deadlines, limited resources and significant risks to quantify and manage their ",wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://en.wikipedia.org/wiki/Project_management_triangle","iron triangle"),"."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["The Estimate Work product is being bootstrapped by Milly and myself and is 100% self-funded. Many key features are still in planning or active development stages. Regardless, our experience with the chosen tech stack and early feedback from the target market are both positive."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h4.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h4.cljs$core$IFn$_invoke$arity$1("Estimate Work's tech stack:") : hoplon.core.h4.call(null,"Estimate Work's tech stack:")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__24704 = (function (){var G__24712 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojure.org/","Clojure");
var G__24713 = " + ";
var G__24714 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojurescript.org/","ClojureScript");
var G__24715 = " for server and client side programming";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24712,G__24713,G__24714,G__24715) : hoplon.core.li.call(null,G__24712,G__24713,G__24714,G__24715));
})();
var G__24705 = (function (){var G__24716 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://blog.estimate-work.com/a-new-world-writing-css-in-clojurescript-and-life-after-sass-bdf5bc80a24f","Garden CSS preprocessor/abstraction");
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$1(G__24716) : hoplon.core.li.call(null,G__24716));
})();
var G__24706 = (function (){var G__24717 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://hoplon.io/","Hoplon");
var G__24718 = " web framework";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24717,G__24718) : hoplon.core.li.call(null,G__24717,G__24718));
})();
var G__24707 = (function (){var G__24719 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/tonsky/datascript","Datascript");
var G__24720 = " as a client-side database";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24719,G__24720) : hoplon.core.li.call(null,G__24719,G__24720));
})();
var G__24708 = (function (){var G__24721 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.rethinkdb.com/","RethinkDB");
var G__24722 = " as a back-end data persistence layer";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24721,G__24722) : hoplon.core.li.call(null,G__24721,G__24722));
})();
var G__24709 = (function (){var G__24723 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://auth0.com/","Auth0");
var G__24724 = " for authentiation/SSO";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24723,G__24724) : hoplon.core.li.call(null,G__24723,G__24724));
})();
var G__24710 = (function (){var G__24725 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://stripe.com/au","Stripe");
var G__24726 = " as payment gateway";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24725,G__24726) : hoplon.core.li.call(null,G__24725,G__24726));
})();
var G__24711 = (function (){var G__24727 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/ptaoussanis/sente","AJAX + WebSockets");
var G__24728 = " for client/server communication";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24727,G__24728) : hoplon.core.li.call(null,G__24727,G__24728));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$8 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$8(G__24704,G__24705,G__24706,G__24707,G__24708,G__24709,G__24710,G__24711) : hoplon.core.ul.call(null,G__24704,G__24705,G__24706,G__24707,G__24708,G__24709,G__24710,G__24711));
})()], 0)),layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0()], 0))], 0))], null);
});
