// Compiled by ClojureScript 1.9.908 {:static-fns true, :optimize-constants true}
goog.provide('pages.dave');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('hoplon.core');
goog.require('layout.content_block');
goog.require('layout.header_block');
goog.require('layout.body_text');
goog.require('image.hoplon');
goog.require('social.hoplon');
goog.require('wheel.abn.core');
goog.require('wheel.link.hoplon');
pages.dave.content = (function pages$dave$content(){
var G__25504 = image.hoplon.header.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.cst$kw$src,"https://s3-ap-southeast-2.amazonaws.com/dim-valley-public/dave-photo.jpg"], 0));
var G__25505 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0(),social.hoplon.icon_links.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.cst$kw$linkedin,"https://www.linkedin.com/in/dmeister/",cljs.core.cst$kw$github,"https://github.com/thedavidmeister",cljs.core.cst$kw$medium,"https://medium.com/@thedavidmeister",cljs.core.cst$kw$twitter,"https://twitter.com/thedavidmeister"], 0))], 0));
var G__25506 = layout.header_block.header("David Meister (Dave)","Owner and consultant at Dim Valley Pty. Ltd. and owner and CTO at Nice Feature Pty. Ltd.");
var G__25507 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("I believe...") : hoplon.core.h2.call(null,"I believe...")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Simple beats complex."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Quality is a process."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Machines are better machines than humans."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Effective systems are composed from effective parts."], 0))], 0));
var G__25508 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Experience") : hoplon.core.h2.call(null,"Experience")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Commercial") : hoplon.core.h3.call(null,"Commercial")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__25510 = (function (){var G__25516 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("10+ years total") : hoplon.core.strong.call(null,"10+ years total"));
var G__25517 = " professional web experience.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25516,G__25517) : hoplon.core.li.call(null,G__25516,G__25517));
})();
var G__25511 = (function (){var G__25518 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Started out") : hoplon.core.strong.call(null,"Started out"));
var G__25519 = " making cool MySpace pages for local indie bands.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25518,G__25519) : hoplon.core.li.call(null,G__25518,G__25519));
})();
var G__25512 = (function (){var G__25520 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("3 years building") : hoplon.core.strong.call(null,"3 years building"));
var G__25521 = " ";
var G__25522 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://furstmedia.com.au/","Furst Media's");
var G__25523 = " publishing platform (10% MoM growth).";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25520,G__25521,G__25522,G__25523) : hoplon.core.li.call(null,G__25520,G__25521,G__25522,G__25523));
})();
var G__25513 = (function (){var G__25524 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("5 years owning and operating") : hoplon.core.strong.call(null,"5 years owning and operating"));
var G__25525 = " my previous digital agency, ";
var G__25526 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2(wheel.abn.core.abr_search_url("58147061121"),"Godel");
var G__25527 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25524,G__25525,G__25526,G__25527) : hoplon.core.li.call(null,G__25524,G__25525,G__25526,G__25527));
})();
var G__25514 = (function (){var G__25528 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("2 years as chief solutions architect") : hoplon.core.strong.call(null,"2 years as chief solutions architect"));
var G__25529 = " at ";
var G__25530 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/","Equiem");
var G__25531 = " ";
var G__25532 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/2016","(100% YoY growth)");
var G__25533 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__25528,G__25529,G__25530,G__25531,G__25532,G__25533) : hoplon.core.li.call(null,G__25528,G__25529,G__25530,G__25531,G__25532,G__25533));
})();
var G__25515 = (function (){var G__25534 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Current owner and CTO") : hoplon.core.strong.call(null,"Current owner and CTO"));
var G__25535 = " of Dim Valley and Nice Feature.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25534,G__25535) : hoplon.core.li.call(null,G__25534,G__25535));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$6(G__25510,G__25511,G__25512,G__25513,G__25514,G__25515) : hoplon.core.ul.call(null,G__25510,G__25511,G__25512,G__25513,G__25514,G__25515));
})()], 0)),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Open source") : hoplon.core.h3.call(null,"Open source")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__25536 = (function (){var G__25541 = (function (){var G__25545 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://drupalcores.com/countries.html","6th in Australia");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__25545) : hoplon.core.strong.call(null,G__25545));
})();
var G__25542 = " for contributions to ";
var G__25543 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.drupal.org/","Drupal");
var G__25544 = " core.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25541,G__25542,G__25543,G__25544) : hoplon.core.li.call(null,G__25541,G__25542,G__25543,G__25544));
})();
var G__25537 = (function (){var G__25546 = (function (){var G__25550 = "Fully automated ";
var G__25551 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/radiant-brook","bitcoin trading bot");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__25550,G__25551) : hoplon.core.strong.call(null,G__25550,G__25551));
})();
var G__25547 = " written in ";
var G__25548 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://symfony.com/","PHP/Symfony");
var G__25549 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25546,G__25547,G__25548,G__25549) : hoplon.core.li.call(null,G__25546,G__25547,G__25548,G__25549));
})();
var G__25538 = (function (){var G__25552 = (function (){var G__25556 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://xoroshiro.di.unimi.it/","Xoroshiro128+");
var G__25557 = " pseudorandom number generator";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__25556,G__25557) : hoplon.core.strong.call(null,G__25556,G__25557));
})();
var G__25553 = " implemented ";
var G__25554 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/xoroshiro128","in clojure");
var G__25555 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25552,G__25553,G__25554,G__25555) : hoplon.core.li.call(null,G__25552,G__25553,G__25554,G__25555));
})();
var G__25539 = (function (){var G__25558 = (function (){var G__25560 = "The ";
var G__25561 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__25562 = " web framework";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$3(G__25560,G__25561,G__25562) : hoplon.core.strong.call(null,G__25560,G__25561,G__25562));
})();
var G__25559 = ", contributing to development, support and documentation.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25558,G__25559) : hoplon.core.li.call(null,G__25558,G__25559));
})();
var G__25540 = (function (){var G__25563 = (function (){var G__25569 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/dim-valley","This website");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__25569) : hoplon.core.strong.call(null,G__25569));
})();
var G__25564 = " built in ";
var G__25565 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__25566 = ", leveraging a ton of ";
var G__25567 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/wheel","my own intellectual property");
var G__25568 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__25563,G__25564,G__25565,G__25566,G__25567,G__25568) : hoplon.core.li.call(null,G__25563,G__25564,G__25565,G__25566,G__25567,G__25568));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$5 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$5(G__25536,G__25537,G__25538,G__25539,G__25540) : hoplon.core.ul.call(null,G__25536,G__25537,G__25538,G__25539,G__25540));
})()], 0))], 0));
var G__25509 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Case studies") : hoplon.core.h2.call(null,"Case studies")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Estimate Work") : hoplon.core.h3.call(null,"Estimate Work")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Estimate Work is a project planning tool designed to assist small teams working with hard deadlines, limited resources and significant risks to quantify and manage their ",wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://en.wikipedia.org/wiki/Project_management_triangle","iron triangle"),"."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["The Estimate Work product is being bootstrapped by Milly and myself and is 100% self-funded. Many key features are still in planning or active development stages. Regardless, our experience with the chosen tech stack and early feedback from the target market are both positive."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.h4.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h4.cljs$core$IFn$_invoke$arity$1("Estimate Work's tech stack:") : hoplon.core.h4.call(null,"Estimate Work's tech stack:")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__25570 = (function (){var G__25578 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojure.org/","Clojure");
var G__25579 = " + ";
var G__25580 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojurescript.org/","ClojureScript");
var G__25581 = " for server and client side programming";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25578,G__25579,G__25580,G__25581) : hoplon.core.li.call(null,G__25578,G__25579,G__25580,G__25581));
})();
var G__25571 = (function (){var G__25582 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://blog.estimate-work.com/a-new-world-writing-css-in-clojurescript-and-life-after-sass-bdf5bc80a24f","Garden CSS preprocessor/abstraction");
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$1(G__25582) : hoplon.core.li.call(null,G__25582));
})();
var G__25572 = (function (){var G__25583 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://hoplon.io/","Hoplon");
var G__25584 = " web framework";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25583,G__25584) : hoplon.core.li.call(null,G__25583,G__25584));
})();
var G__25573 = (function (){var G__25585 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/tonsky/datascript","Datascript");
var G__25586 = " as a client-side database";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25585,G__25586) : hoplon.core.li.call(null,G__25585,G__25586));
})();
var G__25574 = (function (){var G__25587 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.rethinkdb.com/","RethinkDB");
var G__25588 = " as a back-end data persistence layer";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25587,G__25588) : hoplon.core.li.call(null,G__25587,G__25588));
})();
var G__25575 = (function (){var G__25589 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://auth0.com/","Auth0");
var G__25590 = " for authentiation/SSO";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25589,G__25590) : hoplon.core.li.call(null,G__25589,G__25590));
})();
var G__25576 = (function (){var G__25591 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://stripe.com/au","Stripe");
var G__25592 = " as payment gateway";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25591,G__25592) : hoplon.core.li.call(null,G__25591,G__25592));
})();
var G__25577 = (function (){var G__25593 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/ptaoussanis/sente","AJAX + WebSockets");
var G__25594 = " for client/server communication";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25593,G__25594) : hoplon.core.li.call(null,G__25593,G__25594));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$8 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$8(G__25570,G__25571,G__25572,G__25573,G__25574,G__25575,G__25576,G__25577) : hoplon.core.ul.call(null,G__25570,G__25571,G__25572,G__25573,G__25574,G__25575,G__25576,G__25577));
})()], 0)),layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0()], 0))], 0));
return (hoplon.core.div.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.div.cljs$core$IFn$_invoke$arity$6(G__25504,G__25505,G__25506,G__25507,G__25508,G__25509) : hoplon.core.div.call(null,G__25504,G__25505,G__25506,G__25507,G__25508,G__25509));
});
