// Compiled by ClojureScript 1.9.908 {:static-fns true, :optimize-constants true}
goog.provide('pages.dim_valley');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('hoplon.core');
goog.require('layout.header_block');
goog.require('layout.content_block');
goog.require('layout.spacer');
goog.require('our_services.hoplon');
goog.require('layout.body_text');
pages.dim_valley.content = (function pages$dim_valley$content(){
cljs.core.PersistentVector.EMPTY;

var G__25349 = (function (){var G__25351 = cljs.core.cst$kw$css;
var G__25352 = new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$position,"relative"], null);
var G__25353 = (image.hoplon.default_header.cljs$core$IFn$_invoke$arity$0 ? image.hoplon.default_header.cljs$core$IFn$_invoke$arity$0() : image.hoplon.default_header.call(null));
var G__25354 = (function (){var G__25355 = "dim valley";
var G__25356 = cljs.core.cst$kw$css;
var G__25357 = cljs.core.PersistentHashMap.fromArrays([cljs.core.cst$kw$color,cljs.core.cst$kw$text_DASH_align,cljs.core.cst$kw$top,cljs.core.cst$kw$width,cljs.core.cst$kw$right,cljs.core.cst$kw$display,cljs.core.cst$kw$position,cljs.core.cst$kw$letter_DASH_spacing,cljs.core.cst$kw$left],["white","center","50%","100%","0","black","absolute","0.2em","0"]);
return (hoplon.core.h1.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.h1.cljs$core$IFn$_invoke$arity$3(G__25355,G__25356,G__25357) : hoplon.core.h1.call(null,G__25355,G__25356,G__25357));
})();
return (hoplon.core.div.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.div.cljs$core$IFn$_invoke$arity$4(G__25351,G__25352,G__25353,G__25354) : hoplon.core.div.call(null,G__25351,G__25352,G__25353,G__25354));
})();
var G__25350 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Multidisciplinary team of two") : hoplon.core.h2.call(null,"Multidisciplinary team of two")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["We are ",route.hoplon.link.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.cst$kw$handler,cljs.core.cst$kw$milly,"Milly Schmidt"], 0))," and ",route.hoplon.link.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.cst$kw$handler,cljs.core.cst$kw$dave,"Dave Meister"], 0)),"."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["We have worked together for nearly a decade across many businesses, roles, jobs and projects."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Our skills and experience have grown symbiotically together; between us we offer end-to-end web and product services, from ideation and research through to delivery and optimisation."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["We aim to keep Dim Valley small and focussed to suit our lifestyle and personal goals."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["We do just three things under the Dim Valley banner:",(function (){var G__25358 = (function (){var G__25361 = "build sustainable and ";
var G__25362 = (hoplon.core.em.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.em.cljs$core$IFn$_invoke$arity$1("mutually beneficial") : hoplon.core.em.call(null,"mutually beneficial"));
var G__25363 = " relationships with our clients";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$3(G__25361,G__25362,G__25363) : hoplon.core.li.call(null,G__25361,G__25362,G__25363));
})();
var G__25359 = (hoplon.core.li.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$1("facilitate our own personal growth") : hoplon.core.li.call(null,"facilitate our own personal growth"));
var G__25360 = (hoplon.core.li.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$1("dedicate our time and code to better the industry.") : hoplon.core.li.call(null,"dedicate our time and code to better the industry."));
return (hoplon.core.ol.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.ol.cljs$core$IFn$_invoke$arity$3(G__25358,G__25359,G__25360) : hoplon.core.ol.call(null,G__25358,G__25359,G__25360));
})()], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([route.hoplon.link.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.cst$kw$handler,cljs.core.cst$kw$milly,"Read more about Milly's focus and expertise."], 0))], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([route.hoplon.link.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.cst$kw$handler,cljs.core.cst$kw$dave,"Read more about Dave's focus and expertise."], 0))], 0)),(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Modern business services") : hoplon.core.h2.call(null,"Modern business services")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["We have embraced a business-first approach to technology and a human-first approach to product development."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["We work with our clients in an honest and bespoke manner, leveraging our unique expertise to tackle their unique problems."], 0)),our_services.hoplon.service_list(),layout.body_text.p(),pages.work_with_us.link(),(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Some light wordplay") : hoplon.core.h2.call(null,"Some light wordplay")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Dim Valley is a tongue-in-cheek anagram of our names."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Other potentially great options include ",(hoplon.core.em.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.em.cljs$core$IFn$_invoke$arity$1("evilly mad") : hoplon.core.em.call(null,"evilly mad")),", ",(hoplon.core.em.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.em.cljs$core$IFn$_invoke$arity$1("all my dive") : hoplon.core.em.call(null,"all my dive")),", and ",(hoplon.core.em.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.em.cljs$core$IFn$_invoke$arity$1("lively dam") : hoplon.core.em.call(null,"lively dam"))," but we've made our choice and are sticking with it! \uD83D\uDE09"], 0))], 0));
return (hoplon.core.div.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.div.cljs$core$IFn$_invoke$arity$2(G__25349,G__25350) : hoplon.core.div.call(null,G__25349,G__25350));
});
