// Compiled by ClojureScript 1.9.521 {:static-fns true, :optimize-constants true}
goog.provide('pages.dave');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('hoplon.core');
goog.require('layout.content_block');
goog.require('layout.header_block');
goog.require('layout.body_text');
goog.require('image.hoplon');
goog.require('social.hoplon');
goog.require('wheel.abn.core');
goog.require('wheel.link.hoplon');
pages.dave.content = (function pages$dave$content(){
var G__24657 = image.hoplon.cropped.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.cst$kw$src,"https://s3-ap-southeast-2.amazonaws.com/dim-valley-public/dave-photo.jpg",cljs.core.cst$kw$width,"100%",cljs.core.cst$kw$height,"400px",cljs.core.cst$kw$css,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$margin_DASH_bottom,"4px",cljs.core.cst$kw$filter,"saturate(0)"], null)], 0));
var G__24658 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0(),social.hoplon.icon_links.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.cst$kw$linkedin,"https://www.linkedin.com/in/dmeister/",cljs.core.cst$kw$github,"https://github.com/thedavidmeister",cljs.core.cst$kw$medium,"https://medium.com/@thedavidmeister",cljs.core.cst$kw$twitter,"https://twitter.com/thedavidmeister"], 0))], 0));
var G__24659 = layout.header_block.header("David Meister (Dave)","Owner and consultant at Dim Valley Pty. Ltd. and owner and CTO at Nice Feature Pty. Ltd.");
var G__24660 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("I believe...") : hoplon.core.h2.call(null,"I believe...")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Simple beats complex."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Quality is a process."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Machines are better machines than humans."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Effective systems are composed from effective parts."], 0))], 0));
var G__24661 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Experience") : hoplon.core.h2.call(null,"Experience")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Commercial") : hoplon.core.h3.call(null,"Commercial")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__24663 = (function (){var G__24669 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("10+ years total") : hoplon.core.strong.call(null,"10+ years total"));
var G__24670 = " professional web experience.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24669,G__24670) : hoplon.core.li.call(null,G__24669,G__24670));
})();
var G__24664 = (function (){var G__24671 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Started out") : hoplon.core.strong.call(null,"Started out"));
var G__24672 = " making cool MySpace pages for local indie bands.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24671,G__24672) : hoplon.core.li.call(null,G__24671,G__24672));
})();
var G__24665 = (function (){var G__24673 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("3 years building") : hoplon.core.strong.call(null,"3 years building"));
var G__24674 = " ";
var G__24675 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://furstmedia.com.au/","Furst Media's");
var G__24676 = " publishing platform (10% MoM growth).";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24673,G__24674,G__24675,G__24676) : hoplon.core.li.call(null,G__24673,G__24674,G__24675,G__24676));
})();
var G__24666 = (function (){var G__24677 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("5 years owning and operating") : hoplon.core.strong.call(null,"5 years owning and operating"));
var G__24678 = " my previous digital agency, ";
var G__24679 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2(wheel.abn.core.abr_search_url("58147061121"),"Godel");
var G__24680 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24677,G__24678,G__24679,G__24680) : hoplon.core.li.call(null,G__24677,G__24678,G__24679,G__24680));
})();
var G__24667 = (function (){var G__24681 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("2 years as chief solutions architect") : hoplon.core.strong.call(null,"2 years as chief solutions architect"));
var G__24682 = " at ";
var G__24683 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/","Equiem");
var G__24684 = " ";
var G__24685 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/2016","(100% YoY growth)");
var G__24686 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__24681,G__24682,G__24683,G__24684,G__24685,G__24686) : hoplon.core.li.call(null,G__24681,G__24682,G__24683,G__24684,G__24685,G__24686));
})();
var G__24668 = (function (){var G__24687 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Current owner and CTO") : hoplon.core.strong.call(null,"Current owner and CTO"));
var G__24688 = " of Dim Valley and Nice Feature.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24687,G__24688) : hoplon.core.li.call(null,G__24687,G__24688));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$6(G__24663,G__24664,G__24665,G__24666,G__24667,G__24668) : hoplon.core.ul.call(null,G__24663,G__24664,G__24665,G__24666,G__24667,G__24668));
})()], 0)),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Open source") : hoplon.core.h3.call(null,"Open source")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__24689 = (function (){var G__24694 = (function (){var G__24698 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://drupalcores.com/countries.html","6th in Australia");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__24698) : hoplon.core.strong.call(null,G__24698));
})();
var G__24695 = " for contributions to ";
var G__24696 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.drupal.org/","Drupal");
var G__24697 = " core.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24694,G__24695,G__24696,G__24697) : hoplon.core.li.call(null,G__24694,G__24695,G__24696,G__24697));
})();
var G__24690 = (function (){var G__24699 = (function (){var G__24703 = "Fully automated ";
var G__24704 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/radiant-brook","bitcoin trading bot");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__24703,G__24704) : hoplon.core.strong.call(null,G__24703,G__24704));
})();
var G__24700 = " written in ";
var G__24701 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://symfony.com/","PHP/Symfony");
var G__24702 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24699,G__24700,G__24701,G__24702) : hoplon.core.li.call(null,G__24699,G__24700,G__24701,G__24702));
})();
var G__24691 = (function (){var G__24705 = (function (){var G__24709 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://xoroshiro.di.unimi.it/","Xoroshiro128+");
var G__24710 = " pseudorandom number generator";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__24709,G__24710) : hoplon.core.strong.call(null,G__24709,G__24710));
})();
var G__24706 = " implemented ";
var G__24707 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/xoroshiro128","in clojure");
var G__24708 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24705,G__24706,G__24707,G__24708) : hoplon.core.li.call(null,G__24705,G__24706,G__24707,G__24708));
})();
var G__24692 = (function (){var G__24711 = (function (){var G__24713 = "The ";
var G__24714 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__24715 = " web framework";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$3(G__24713,G__24714,G__24715) : hoplon.core.strong.call(null,G__24713,G__24714,G__24715));
})();
var G__24712 = ", contributing to development, support and documentation.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24711,G__24712) : hoplon.core.li.call(null,G__24711,G__24712));
})();
var G__24693 = (function (){var G__24716 = (function (){var G__24722 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/dim-valley","This website");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__24722) : hoplon.core.strong.call(null,G__24722));
})();
var G__24717 = " built in ";
var G__24718 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__24719 = ", leveraging a ton of ";
var G__24720 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/wheel","my own intellectual property");
var G__24721 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__24716,G__24717,G__24718,G__24719,G__24720,G__24721) : hoplon.core.li.call(null,G__24716,G__24717,G__24718,G__24719,G__24720,G__24721));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$5 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$5(G__24689,G__24690,G__24691,G__24692,G__24693) : hoplon.core.ul.call(null,G__24689,G__24690,G__24691,G__24692,G__24693));
})()], 0))], 0));
var G__24662 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Case studies") : hoplon.core.h2.call(null,"Case studies")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Estimate Work") : hoplon.core.h3.call(null,"Estimate Work")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Estimate Work is a project planning tool designed to assist small teams working with hard deadlines, limited resources and significant risks to quantify and manage their ",wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://en.wikipedia.org/wiki/Project_management_triangle","iron triangle"),"."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["The Estimate Work product is being bootstrapped by Milly and myself and is 100% self-funded. Many key features are still in planning or active development stages. Regardless, our experience with the chosen tech stack and early feedback from the target market are both positive."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h4.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h4.cljs$core$IFn$_invoke$arity$1("Estimate Work's tech stack:") : hoplon.core.h4.call(null,"Estimate Work's tech stack:")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__24723 = (function (){var G__24731 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojure.org/","Clojure");
var G__24732 = " + ";
var G__24733 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojurescript.org/","ClojureScript");
var G__24734 = " for server and client side programming";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__24731,G__24732,G__24733,G__24734) : hoplon.core.li.call(null,G__24731,G__24732,G__24733,G__24734));
})();
var G__24724 = (function (){var G__24735 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://blog.estimate-work.com/a-new-world-writing-css-in-clojurescript-and-life-after-sass-bdf5bc80a24f","Garden CSS preprocessor/abstraction");
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$1(G__24735) : hoplon.core.li.call(null,G__24735));
})();
var G__24725 = (function (){var G__24736 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://hoplon.io/","Hoplon");
var G__24737 = " web framework";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24736,G__24737) : hoplon.core.li.call(null,G__24736,G__24737));
})();
var G__24726 = (function (){var G__24738 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/tonsky/datascript","Datascript");
var G__24739 = " as a client-side database";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24738,G__24739) : hoplon.core.li.call(null,G__24738,G__24739));
})();
var G__24727 = (function (){var G__24740 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.rethinkdb.com/","RethinkDB");
var G__24741 = " as a back-end data persistence layer";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24740,G__24741) : hoplon.core.li.call(null,G__24740,G__24741));
})();
var G__24728 = (function (){var G__24742 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://auth0.com/","Auth0");
var G__24743 = " for authentiation/SSO";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24742,G__24743) : hoplon.core.li.call(null,G__24742,G__24743));
})();
var G__24729 = (function (){var G__24744 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://stripe.com/au","Stripe");
var G__24745 = " as payment gateway";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24744,G__24745) : hoplon.core.li.call(null,G__24744,G__24745));
})();
var G__24730 = (function (){var G__24746 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/ptaoussanis/sente","AJAX + WebSockets");
var G__24747 = " for client/server communication";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__24746,G__24747) : hoplon.core.li.call(null,G__24746,G__24747));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$8 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$8(G__24723,G__24724,G__24725,G__24726,G__24727,G__24728,G__24729,G__24730) : hoplon.core.ul.call(null,G__24723,G__24724,G__24725,G__24726,G__24727,G__24728,G__24729,G__24730));
})()], 0)),layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0()], 0))], 0));
return (hoplon.core.div.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.div.cljs$core$IFn$_invoke$arity$6(G__24657,G__24658,G__24659,G__24660,G__24661,G__24662) : hoplon.core.div.call(null,G__24657,G__24658,G__24659,G__24660,G__24661,G__24662));
});
