// Compiled by ClojureScript 1.9.521 {:static-fns true, :optimize-constants true}
goog.provide('pages.dave');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('hoplon.core');
goog.require('layout.content_block');
goog.require('layout.header_block');
goog.require('layout.body_text');
goog.require('image.hoplon');
goog.require('social.hoplon');
goog.require('wheel.abn.core');
goog.require('wheel.link.hoplon');
pages.dave.content = (function pages$dave$content(){
var G__20691 = image.hoplon.cropped.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.cst$kw$src,"https://s3-ap-southeast-2.amazonaws.com/dim-valley-public/dave-photo.jpg",cljs.core.cst$kw$width,"100%",cljs.core.cst$kw$height,"400px",cljs.core.cst$kw$css,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$margin_DASH_bottom,"4px",cljs.core.cst$kw$filter,"saturate(0)"], null)], 0));
var G__20692 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0 ? layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0() : layout.spacer.vertical_spacer.call(null)),social.hoplon.icon_links.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.cst$kw$linkedin,"https://www.linkedin.com/in/dmeister/",cljs.core.cst$kw$github,"https://github.com/thedavidmeister",cljs.core.cst$kw$medium,"https://medium.com/@thedavidmeister",cljs.core.cst$kw$twitter,"https://twitter.com/thedavidmeister"], 0))], 0));
var G__20693 = layout.header_block.header("David Meister (Dave)","Owner and consultant at Dim Valley Pty. Ltd. and owner and CTO at Nice Feature Pty. Ltd.");
var G__20694 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("I believe...") : hoplon.core.h2.call(null,"I believe...")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Simple beats complex."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Quality is a process."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Machines are better machines than humans."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Effective systems are composed from effective parts."], 0))], 0));
var G__20695 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Experience") : hoplon.core.h2.call(null,"Experience")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Commercial") : hoplon.core.h3.call(null,"Commercial")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__20697 = (function (){var G__20703 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("10+ years total") : hoplon.core.strong.call(null,"10+ years total"));
var G__20704 = " professional web experience.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20703,G__20704) : hoplon.core.li.call(null,G__20703,G__20704));
})();
var G__20698 = (function (){var G__20705 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Started out") : hoplon.core.strong.call(null,"Started out"));
var G__20706 = " making cool MySpace pages for local indie bands.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20705,G__20706) : hoplon.core.li.call(null,G__20705,G__20706));
})();
var G__20699 = (function (){var G__20707 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("3 years building") : hoplon.core.strong.call(null,"3 years building"));
var G__20708 = " ";
var G__20709 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://furstmedia.com.au/","Furst Media's");
var G__20710 = " publishing platform (10% MoM growth).";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__20707,G__20708,G__20709,G__20710) : hoplon.core.li.call(null,G__20707,G__20708,G__20709,G__20710));
})();
var G__20700 = (function (){var G__20711 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("5 years owning and operating") : hoplon.core.strong.call(null,"5 years owning and operating"));
var G__20712 = " my previous digital agency, ";
var G__20713 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2(wheel.abn.core.abr_search_url("58147061121"),"Godel");
var G__20714 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__20711,G__20712,G__20713,G__20714) : hoplon.core.li.call(null,G__20711,G__20712,G__20713,G__20714));
})();
var G__20701 = (function (){var G__20715 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("2 years as chief solutions architect") : hoplon.core.strong.call(null,"2 years as chief solutions architect"));
var G__20716 = " at ";
var G__20717 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/","Equiem");
var G__20718 = " ";
var G__20719 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/2016","(100% YoY growth)");
var G__20720 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__20715,G__20716,G__20717,G__20718,G__20719,G__20720) : hoplon.core.li.call(null,G__20715,G__20716,G__20717,G__20718,G__20719,G__20720));
})();
var G__20702 = (function (){var G__20721 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Current owner and CTO") : hoplon.core.strong.call(null,"Current owner and CTO"));
var G__20722 = " of Dim Valley and Nice Feature.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20721,G__20722) : hoplon.core.li.call(null,G__20721,G__20722));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$6(G__20697,G__20698,G__20699,G__20700,G__20701,G__20702) : hoplon.core.ul.call(null,G__20697,G__20698,G__20699,G__20700,G__20701,G__20702));
})()], 0)),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Open source") : hoplon.core.h3.call(null,"Open source")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__20723 = (function (){var G__20728 = (function (){var G__20732 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://drupalcores.com/countries.html","6th in Australia");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__20732) : hoplon.core.strong.call(null,G__20732));
})();
var G__20729 = " for contributions to ";
var G__20730 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.drupal.org/","Drupal");
var G__20731 = " core.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__20728,G__20729,G__20730,G__20731) : hoplon.core.li.call(null,G__20728,G__20729,G__20730,G__20731));
})();
var G__20724 = (function (){var G__20733 = (function (){var G__20737 = "Fully automated ";
var G__20738 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/radiant-brook","bitcoin trading bot");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__20737,G__20738) : hoplon.core.strong.call(null,G__20737,G__20738));
})();
var G__20734 = " written in ";
var G__20735 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://symfony.com/","PHP/Symfony");
var G__20736 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__20733,G__20734,G__20735,G__20736) : hoplon.core.li.call(null,G__20733,G__20734,G__20735,G__20736));
})();
var G__20725 = (function (){var G__20739 = (function (){var G__20743 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://xoroshiro.di.unimi.it/","Xoroshiro128+");
var G__20744 = " pseudorandom number generator";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__20743,G__20744) : hoplon.core.strong.call(null,G__20743,G__20744));
})();
var G__20740 = " implemented ";
var G__20741 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/xoroshiro128","in clojure");
var G__20742 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__20739,G__20740,G__20741,G__20742) : hoplon.core.li.call(null,G__20739,G__20740,G__20741,G__20742));
})();
var G__20726 = (function (){var G__20745 = (function (){var G__20747 = "The ";
var G__20748 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__20749 = " web framework";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$3(G__20747,G__20748,G__20749) : hoplon.core.strong.call(null,G__20747,G__20748,G__20749));
})();
var G__20746 = ", contributing to development, support and documentation.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20745,G__20746) : hoplon.core.li.call(null,G__20745,G__20746));
})();
var G__20727 = (function (){var G__20750 = (function (){var G__20756 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/dim-valley","This website");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__20756) : hoplon.core.strong.call(null,G__20756));
})();
var G__20751 = " built in ";
var G__20752 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__20753 = ", leveraging a ton of ";
var G__20754 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/wheel","my own intellectual property");
var G__20755 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__20750,G__20751,G__20752,G__20753,G__20754,G__20755) : hoplon.core.li.call(null,G__20750,G__20751,G__20752,G__20753,G__20754,G__20755));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$5 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$5(G__20723,G__20724,G__20725,G__20726,G__20727) : hoplon.core.ul.call(null,G__20723,G__20724,G__20725,G__20726,G__20727));
})()], 0))], 0));
var G__20696 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Case studies") : hoplon.core.h2.call(null,"Case studies")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Estimate Work") : hoplon.core.h3.call(null,"Estimate Work")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["Estimate Work is a project planning tool designed to assist small teams working with hard deadlines, limited resources and significant risks to quantify and manage their ",wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://en.wikipedia.org/wiki/Project_management_triangle","iron triangle"),"."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq(["The Estimate Work product is being bootstrapped by Milly and myself and is 100% self-funded. Many key features are still in planning or active development stages. Regardless, our experience with the chosen tech stack and early feedback from the target market are both positive."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(hoplon.core.h4.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h4.cljs$core$IFn$_invoke$arity$1("Estimate Work's tech stack:") : hoplon.core.h4.call(null,"Estimate Work's tech stack:")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__20757 = (function (){var G__20765 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojure.org/","Clojure");
var G__20766 = " + ";
var G__20767 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojurescript.org/","ClojureScript");
var G__20768 = " for server and client side programming";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__20765,G__20766,G__20767,G__20768) : hoplon.core.li.call(null,G__20765,G__20766,G__20767,G__20768));
})();
var G__20758 = (function (){var G__20769 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://blog.estimate-work.com/a-new-world-writing-css-in-clojurescript-and-life-after-sass-bdf5bc80a24f","Garden CSS preprocessor/abstraction");
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$1(G__20769) : hoplon.core.li.call(null,G__20769));
})();
var G__20759 = (function (){var G__20770 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://hoplon.io/","Hoplon");
var G__20771 = " web framework";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20770,G__20771) : hoplon.core.li.call(null,G__20770,G__20771));
})();
var G__20760 = (function (){var G__20772 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/tonsky/datascript","Datascript");
var G__20773 = " as a client-side database";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20772,G__20773) : hoplon.core.li.call(null,G__20772,G__20773));
})();
var G__20761 = (function (){var G__20774 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.rethinkdb.com/","RethinkDB");
var G__20775 = " as a back-end data persistence layer";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20774,G__20775) : hoplon.core.li.call(null,G__20774,G__20775));
})();
var G__20762 = (function (){var G__20776 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://auth0.com/","Auth0");
var G__20777 = " for authentiation/SSO";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20776,G__20777) : hoplon.core.li.call(null,G__20776,G__20777));
})();
var G__20763 = (function (){var G__20778 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://stripe.com/au","Stripe");
var G__20779 = " as payment gateway";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20778,G__20779) : hoplon.core.li.call(null,G__20778,G__20779));
})();
var G__20764 = (function (){var G__20780 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/ptaoussanis/sente","AJAX + WebSockets");
var G__20781 = " for client/server communication";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__20780,G__20781) : hoplon.core.li.call(null,G__20780,G__20781));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$8 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$8(G__20757,G__20758,G__20759,G__20760,G__20761,G__20762,G__20763,G__20764) : hoplon.core.ul.call(null,G__20757,G__20758,G__20759,G__20760,G__20761,G__20762,G__20763,G__20764));
})()], 0)),(layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0 ? layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0() : layout.spacer.vertical_spacer.call(null))], 0))], 0));
return (hoplon.core.div.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.div.cljs$core$IFn$_invoke$arity$6(G__20691,G__20692,G__20693,G__20694,G__20695,G__20696) : hoplon.core.div.call(null,G__20691,G__20692,G__20693,G__20694,G__20695,G__20696));
});
