// Compiled by ClojureScript 1.9.908 {:static-fns true, :optimize-constants true}
goog.provide('pages.dave');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('hoplon.core');
goog.require('layout.content_block');
goog.require('layout.header_block');
goog.require('layout.body_text');
goog.require('image.hoplon');
goog.require('social.hoplon');
goog.require('wheel.abn.core');
goog.require('wheel.link.hoplon');
pages.dave.content = (function pages$dave$content(){
var G__25577 = image.hoplon.header.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.cst$kw$src,"https://s3-ap-southeast-2.amazonaws.com/dim-valley-public/dave-photo.jpg"], 0));
var G__25578 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([social.hoplon.icon_links.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.cst$kw$linkedin,"https://www.linkedin.com/in/dmeister/",cljs.core.cst$kw$github,"https://github.com/thedavidmeister",cljs.core.cst$kw$medium,"https://medium.com/@thedavidmeister",cljs.core.cst$kw$twitter,"https://twitter.com/thedavidmeister"], 0)),layout.header_block.header("David Meister (Dave)","Owner and consultant at Dim Valley Pty. Ltd. and owner and CTO at Nice Feature Pty. Ltd."),(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("I believe...") : hoplon.core.h2.call(null,"I believe...")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Simple beats complex."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Quality is a process."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Machines are better machines than humans."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Effective systems are composed from effective parts."], 0)),(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Experience") : hoplon.core.h2.call(null,"Experience")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Commercial") : hoplon.core.h3.call(null,"Commercial")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__25579 = (function (){var G__25585 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("10+ years total") : hoplon.core.strong.call(null,"10+ years total"));
var G__25586 = " professional web experience.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25585,G__25586) : hoplon.core.li.call(null,G__25585,G__25586));
})();
var G__25580 = (function (){var G__25587 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Started out") : hoplon.core.strong.call(null,"Started out"));
var G__25588 = " making cool MySpace pages for local indie bands.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25587,G__25588) : hoplon.core.li.call(null,G__25587,G__25588));
})();
var G__25581 = (function (){var G__25589 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("3 years building") : hoplon.core.strong.call(null,"3 years building"));
var G__25590 = " ";
var G__25591 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://furstmedia.com.au/","Furst Media's");
var G__25592 = " publishing platform (10% MoM growth).";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25589,G__25590,G__25591,G__25592) : hoplon.core.li.call(null,G__25589,G__25590,G__25591,G__25592));
})();
var G__25582 = (function (){var G__25593 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("5 years owning and operating") : hoplon.core.strong.call(null,"5 years owning and operating"));
var G__25594 = " my previous digital agency, ";
var G__25595 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2(wheel.abn.core.abr_search_url("58147061121"),"Godel");
var G__25596 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25593,G__25594,G__25595,G__25596) : hoplon.core.li.call(null,G__25593,G__25594,G__25595,G__25596));
})();
var G__25583 = (function (){var G__25597 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("2 years as chief solutions architect") : hoplon.core.strong.call(null,"2 years as chief solutions architect"));
var G__25598 = " at ";
var G__25599 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/","Equiem");
var G__25600 = " ";
var G__25601 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://equiem.com.au/2016","(100% YoY growth)");
var G__25602 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__25597,G__25598,G__25599,G__25600,G__25601,G__25602) : hoplon.core.li.call(null,G__25597,G__25598,G__25599,G__25600,G__25601,G__25602));
})();
var G__25584 = (function (){var G__25603 = (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Current owner and CTO") : hoplon.core.strong.call(null,"Current owner and CTO"));
var G__25604 = " of Dim Valley and Nice Feature.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25603,G__25604) : hoplon.core.li.call(null,G__25603,G__25604));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$6(G__25579,G__25580,G__25581,G__25582,G__25583,G__25584) : hoplon.core.ul.call(null,G__25579,G__25580,G__25581,G__25582,G__25583,G__25584));
})()], 0)),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Open source") : hoplon.core.h3.call(null,"Open source")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__25605 = (function (){var G__25610 = (function (){var G__25614 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://drupalcores.com/countries.html","6th in Australia");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__25614) : hoplon.core.strong.call(null,G__25614));
})();
var G__25611 = " for contributions to ";
var G__25612 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.drupal.org/","Drupal");
var G__25613 = " core.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25610,G__25611,G__25612,G__25613) : hoplon.core.li.call(null,G__25610,G__25611,G__25612,G__25613));
})();
var G__25606 = (function (){var G__25615 = (function (){var G__25619 = "Fully automated ";
var G__25620 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/radiant-brook","bitcoin trading bot");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__25619,G__25620) : hoplon.core.strong.call(null,G__25619,G__25620));
})();
var G__25616 = " written in ";
var G__25617 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://symfony.com/","PHP/Symfony");
var G__25618 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25615,G__25616,G__25617,G__25618) : hoplon.core.li.call(null,G__25615,G__25616,G__25617,G__25618));
})();
var G__25607 = (function (){var G__25621 = (function (){var G__25625 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://xoroshiro.di.unimi.it/","Xoroshiro128+");
var G__25626 = " pseudorandom number generator";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$2(G__25625,G__25626) : hoplon.core.strong.call(null,G__25625,G__25626));
})();
var G__25622 = " implemented ";
var G__25623 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/xoroshiro128","in clojure");
var G__25624 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25621,G__25622,G__25623,G__25624) : hoplon.core.li.call(null,G__25621,G__25622,G__25623,G__25624));
})();
var G__25608 = (function (){var G__25627 = (function (){var G__25629 = "The ";
var G__25630 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__25631 = " web framework";
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$3(G__25629,G__25630,G__25631) : hoplon.core.strong.call(null,G__25629,G__25630,G__25631));
})();
var G__25628 = ", contributing to development, support and documentation.";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25627,G__25628) : hoplon.core.li.call(null,G__25627,G__25628));
})();
var G__25609 = (function (){var G__25632 = (function (){var G__25638 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/dim-valley","This website");
return (hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1(G__25638) : hoplon.core.strong.call(null,G__25638));
})();
var G__25633 = " built in ";
var G__25634 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://hoplon.io/","Hoplon");
var G__25635 = ", leveraging a ton of ";
var G__25636 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/thedavidmeister/wheel","my own intellectual property");
var G__25637 = ".";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$6 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$6(G__25632,G__25633,G__25634,G__25635,G__25636,G__25637) : hoplon.core.li.call(null,G__25632,G__25633,G__25634,G__25635,G__25636,G__25637));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$5 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$5(G__25605,G__25606,G__25607,G__25608,G__25609) : hoplon.core.ul.call(null,G__25605,G__25606,G__25607,G__25608,G__25609));
})()], 0)),(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Case studies") : hoplon.core.h2.call(null,"Case studies")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("Estimate Work") : hoplon.core.h3.call(null,"Estimate Work")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Estimate Work is a project planning tool designed to assist small teams working with hard deadlines, limited resources and significant risks to quantify and manage their ",wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://en.wikipedia.org/wiki/Project_management_triangle","iron triangle"),"."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["The Estimate Work product is being bootstrapped by Milly and myself and is 100% self-funded. Many key features are still in planning or active development stages. Regardless, our experience with the chosen tech stack and early feedback from the target market are both positive."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.h4.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h4.cljs$core$IFn$_invoke$arity$1("Estimate Work's tech stack:") : hoplon.core.h4.call(null,"Estimate Work's tech stack:")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__25639 = (function (){var G__25647 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojure.org/","Clojure");
var G__25648 = " + ";
var G__25649 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://clojurescript.org/","ClojureScript");
var G__25650 = " for server and client side programming";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$4(G__25647,G__25648,G__25649,G__25650) : hoplon.core.li.call(null,G__25647,G__25648,G__25649,G__25650));
})();
var G__25640 = (function (){var G__25651 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://blog.estimate-work.com/a-new-world-writing-css-in-clojurescript-and-life-after-sass-bdf5bc80a24f","Garden CSS preprocessor/abstraction");
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$1(G__25651) : hoplon.core.li.call(null,G__25651));
})();
var G__25641 = (function (){var G__25652 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("http://hoplon.io/","Hoplon");
var G__25653 = " web framework";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25652,G__25653) : hoplon.core.li.call(null,G__25652,G__25653));
})();
var G__25642 = (function (){var G__25654 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/tonsky/datascript","Datascript");
var G__25655 = " as a client-side database";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25654,G__25655) : hoplon.core.li.call(null,G__25654,G__25655));
})();
var G__25643 = (function (){var G__25656 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://www.rethinkdb.com/","RethinkDB");
var G__25657 = " as a back-end data persistence layer";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25656,G__25657) : hoplon.core.li.call(null,G__25656,G__25657));
})();
var G__25644 = (function (){var G__25658 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://auth0.com/","Auth0");
var G__25659 = " for authentiation/SSO";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25658,G__25659) : hoplon.core.li.call(null,G__25658,G__25659));
})();
var G__25645 = (function (){var G__25660 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://stripe.com/au","Stripe");
var G__25661 = " as payment gateway";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25660,G__25661) : hoplon.core.li.call(null,G__25660,G__25661));
})();
var G__25646 = (function (){var G__25662 = wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://github.com/ptaoussanis/sente","AJAX + WebSockets");
var G__25663 = " for client/server communication";
return (hoplon.core.li.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.li.cljs$core$IFn$_invoke$arity$2(G__25662,G__25663) : hoplon.core.li.call(null,G__25662,G__25663));
})();
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$8 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$8(G__25639,G__25640,G__25641,G__25642,G__25643,G__25644,G__25645,G__25646) : hoplon.core.ul.call(null,G__25639,G__25640,G__25641,G__25642,G__25643,G__25644,G__25645,G__25646));
})()], 0))], 0))], 0));
return (hoplon.core.div.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.div.cljs$core$IFn$_invoke$arity$2(G__25577,G__25578) : hoplon.core.div.call(null,G__25577,G__25578));
});
