// Compiled by ClojureScript 1.9.908 {:static-fns true, :optimize-constants true}
goog.provide('pages.work_with_us');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('hoplon.core');
goog.require('layout.header_block');
goog.require('layout.content_block');
goog.require('layout.spacer');
goog.require('image.hoplon');
goog.require('layout.body_text');
goog.require('wheel.link.hoplon');
pages.work_with_us.content = (function pages$work_with_us$content(){
var G__24797 = image.hoplon.header.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.cst$kw$src,"https://s3-ap-southeast-2.amazonaws.com/estimatework/collab.jpeg"], 0));
var G__24798 = layout.header_block.header("Work with us","Our rates and availability");
var G__24799 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Our availability") : hoplon.core.h2.call(null,"Our availability")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Building ",wheel.link.hoplon.external.cljs$core$IFn$_invoke$arity$2("https://estimate-work.com/","Estimate Work")," is currently our primary focus, limiting our overall availability, but we are happy to provide services to new and existing clients on an ad-hoc basis."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["We work on a contract basis on projects with clearly defined scope and deliverables."], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Dave") : hoplon.core.strong.call(null,"Dave"))," is available ",(hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("up to 3 days per week. ") : hoplon.core.strong.call(null,"up to 3 days per week. ")),(hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Milly") : hoplon.core.strong.call(null,"Milly"))," is available ",(hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("up to 2 days per week.") : hoplon.core.strong.call(null,"up to 2 days per week."))], 0)),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Our preference is for most or all project work to be ",(hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("conducted remotely") : hoplon.core.strong.call(null,"conducted remotely")),", using common telecommute technologies such as Google Hangouts, Slack, Flowdock, etc. to stay connected and in sync. We are able to commute to locations in central Melbourne for meetings, research or other discrete tasks."], 0))], 0));
var G__24800 = layout.content_block.content_inner.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("Our rates") : hoplon.core.h2.call(null,"Our rates")),layout.body_text.p.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Our hourly rate:") : hoplon.core.strong.call(null,"Our hourly rate:"))," $AUD 120 + GST",(hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null)),(hoplon.core.strong.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.strong.cljs$core$IFn$_invoke$arity$1("Our day rate (prebooked):") : hoplon.core.strong.call(null,"Our day rate (prebooked):"))," $AUD 800 + GST"], 0)),layout.spacer.vertical_spacer.cljs$core$IFn$_invoke$arity$0()], 0));
return (hoplon.core.div.cljs$core$IFn$_invoke$arity$4 ? hoplon.core.div.cljs$core$IFn$_invoke$arity$4(G__24797,G__24798,G__24799,G__24800) : hoplon.core.div.call(null,G__24797,G__24798,G__24799,G__24800));
});
