version: 2

jobs:
 deploy:
  # docker:
  #  - image: nixorg/nix:circleci
  steps:
   - curl https://nixos.org/nix/install | sh
   - checkout
   - run: nix-shell --run 'boot deploy'

workflows:
 version: 2
 deploy:
  jobs:
   - deploy:
      filters:
       branches:
        only:
         - master
